heat_template_version: 2013-05-23

description: >
  Heat template for managing Cassandra nodes in OpenStack cloud

parameters:
  key_name:
    type: string
    default: rushi
    constraints:
      - custom_constraint: nova.keypair
  flavor:
    type: string
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    default: cassandra
    constraints:
      - custom_constraint: glance.image

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      user_data: |
          echo "done" >> /tmp/status.txt

outputs:
    server_networks:
        value: { get_attr: [server, networks] }
